name: Composite java action
description: Setup JDK and maven
inputs:
    aws-region:
      description: AWS region of the ECR repo
      required: false
      default: ap-south-1
    aws-ecr-repo-base:
      description: Private ECR repository base path
      required: false
      default: tux/image-repo
    aws-account-id:
      description: AWS account ID with OIDC
      required: true
    image-name:
      description: image name
      required: false
      default: demo-app
    image-version:
      description: image version
      required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.aws-ecr-repo-base }}
        IMAGE_TAG: ${{ inputs.image-name }}-${{ inputs.image-version }}
      shell: bash
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG